services:
  book-keeper:
    image: kvqn/book-keeper:latest
    environment:
      - |
        WATCH_DIRS=
        /watch/library
        /watch/imports
      - INGESTION_DIR=/ingestion
      - RECORDS_FILE=/data/records.json
      - STABILIZATION_SECS=5
      - SCAN_ON_STARTUP=true
    volumes:
      - ./library:/watch/library:ro
      - ./imports:/watch/imports:ro
      - ./ingestion:/ingestion
      - ./data:/data
    restart: unless-stopped
